#!/usr/bin/env bash

cp /etc/squid/squid.conf /etc/squid/squid.conf~

IP=$(wget -4qO- "http://whatismyip.akamai.com/")
DOCKER_IP=$(ip route show | awk '/default/ {print $3}')

cat > /etc/squid/squid.conf <<END
http_port $PROXY_PORT
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl REMOTE_SELF dst $IP/32
acl DOCKER_IP dst $DOCKER_IP/32
http_access allow REMOTE_SELF
http_access allow DOCKER_IP
http_access allow localhost
http_access deny all
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
END

echo "Proxy IP: $IP"
echo "Docker IP: $DOCKER_IP"

squid -f /etc/squid/squid.conf -NC
